server:
  port: 9003

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: TEAM-SERVICE
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team/**
          filters:
            - AuthenticationFilter

        - id: PLAYER-SERVICE
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/player/**
          filters:
            - AuthenticationFilter

        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**