spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/teamdb?autoReconnect=true&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Team-Service
server:
  port: 9000

resilience4j:
  circuit-breaker:
    instances:
      PlayerServiceFallback:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      PlayerServiceFallback:
        waitDuration: 2s
        maxAttempts: 3

  rate-limiter:
    instances:
      TeamServiceLimiter:
        timeoutDuration: 0s
        limitForPeriod: 2
        limitRefreshPeriod: 4s





